version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test/

permissions:
  - object: /home/ec2-user/test/script
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 750

hooks:
  ApplicationStop:
    - location: /script/docker-stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /script/docker-pull.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /script/docker-run.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: /script/validation.sh
      timeout: 240
      runas: root
