version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/test/

permissions:
  - object: /home/ec2-user/test/script
    pattern : "*.sh"
    owner: root
    group: root
    mode: 750
    type:
      - file
hooks:
  ApplicationStop:
    - location: /script/docker-stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /script/docker-pull.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /script/docker-run.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: /script/validation.sh
      timeout: 240
      runas: root