version: "3"
services:
  nginx:
    image: khu3000/nginx:0.1
    ports:
      - 80:80
    depends_on:
      - docker-springboot
  docker-springboot:
    image: khu3000/springboot:0.1
    expose:
      - 8080